/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as MyReservationsRouteImport } from './routes/my-reservations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BorrowRouteImport } from './routes/borrow'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminResourcesRouteImport } from './routes/admin/resources'
import { Route as AdminReservationsRouteImport } from './routes/admin/reservations'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAuthRouteImport } from './routes/admin/auth'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReservationsRoute = MyReservationsRouteImport.update({
  id: '/my-reservations',
  path: '/my-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowRoute = BorrowRouteImport.update({
  id: '/borrow',
  path: '/borrow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/admin/resources',
  path: '/admin/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/admin/reservations',
  path: '/admin/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/borrow': typeof BorrowRoute
  '/dashboard': typeof DashboardRoute
  '/my-reservations': typeof MyReservationsRoute
  '/reservations': typeof ReservationsRoute
  '/resources': typeof ResourcesRoute
  '/students': typeof StudentsRoute
  '/tags': typeof TagsRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/borrow': typeof BorrowRoute
  '/dashboard': typeof DashboardRoute
  '/my-reservations': typeof MyReservationsRoute
  '/reservations': typeof ReservationsRoute
  '/resources': typeof ResourcesRoute
  '/students': typeof StudentsRoute
  '/tags': typeof TagsRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/borrow': typeof BorrowRoute
  '/dashboard': typeof DashboardRoute
  '/my-reservations': typeof MyReservationsRoute
  '/reservations': typeof ReservationsRoute
  '/resources': typeof ResourcesRoute
  '/students': typeof StudentsRoute
  '/tags': typeof TagsRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/borrow'
    | '/dashboard'
    | '/my-reservations'
    | '/reservations'
    | '/resources'
    | '/students'
    | '/tags'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/admin/reservations'
    | '/admin/resources'
    | '/admin/students'
    | '/admin/tags'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/borrow'
    | '/dashboard'
    | '/my-reservations'
    | '/reservations'
    | '/resources'
    | '/students'
    | '/tags'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/admin/reservations'
    | '/admin/resources'
    | '/admin/students'
    | '/admin/tags'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/borrow'
    | '/dashboard'
    | '/my-reservations'
    | '/reservations'
    | '/resources'
    | '/students'
    | '/tags'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/admin/reservations'
    | '/admin/resources'
    | '/admin/students'
    | '/admin/tags'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BorrowRoute: typeof BorrowRoute
  DashboardRoute: typeof DashboardRoute
  MyReservationsRoute: typeof MyReservationsRoute
  ReservationsRoute: typeof ReservationsRoute
  ResourcesRoute: typeof ResourcesRoute
  StudentsRoute: typeof StudentsRoute
  TagsRoute: typeof TagsRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reservations': {
      id: '/my-reservations'
      path: '/my-reservations'
      fullPath: '/my-reservations'
      preLoaderRoute: typeof MyReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrow': {
      id: '/borrow'
      path: '/borrow'
      fullPath: '/borrow'
      preLoaderRoute: typeof BorrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/admin/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/admin/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BorrowRoute: BorrowRoute,
  DashboardRoute: DashboardRoute,
  MyReservationsRoute: MyReservationsRoute,
  ReservationsRoute: ReservationsRoute,
  ResourcesRoute: ResourcesRoute,
  StudentsRoute: StudentsRoute,
  TagsRoute: TagsRoute,
  AdminAuthRoute: AdminAuthRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
